			<option title="" class="emji">😁</option>
			<option title="" class="emji">😂</option>
			<option title="" class="emji">😃</option>
			<option title="" class="emji">😄</option>
			<option title="" class="emji">😅</option>
			<option title="" class="emji">😆</option>
			<option title="" class="emji">😇</option>
			<option title="" class="emji">😈</option>
			<option title="" class="emji">😉</option>
			<option title="" class="emji">😊</option>
			<option title="" class="emji">😋</option>
			<option title="" class="emji">😌</option>
			<option title="" class="emji">😍</option>
			<option title="" class="emji">😎</option>
			<option title="" class="emji">😏</option>
			<option title="" class="emji">😐</option>
			<option title="" class="emji">😒</option>
			<option title="" class="emji">😓</option>
			<option title="" class="emji">😔</option>
			<option title="" class="emji">😖</option>
			<option title="" class="emji">😘</option>
			<option title="" class="emji">😚</option>
			<option title="" class="emji">😜</option>
			<option title="" class="emji">😝</option>
			<option title="" class="emji">😞</option>
			<option title="" class="emji">😠</option>
			<option title="" class="emji">😡</option>
			<option title="" class="emji">😢</option>
			<option title="" class="emji">😣</option>
			<option title="" class="emji">😤</option>
			<option title="" class="emji">😥</option>
			<option title="" class="emji">😨</option>
			<option title="" class="emji">😩</option>
			<option title="" class="emji">😪</option>
			<option title="" class="emji">😫</option>
			<option title="" class="emji">😭</option>
			<option title="" class="emji">😰</option>
			<option title="" class="emji">😱</option>
			<option title="" class="emji">😲</option>
			<option title="" class="emji">😳</option>
			<option title="" class="emji">😵</option>
			<option title="" class="emji">😶</option>
			<option title="" class="emji">😷</option>
			<option title="" class="emji">😸</option>
			<option title="" class="emji">😹</option>
			<option title="" class="emji">😺</option>
			<option title="" class="emji">😻</option>
			<option title="" class="emji">😼</option>
			<option title="" class="emji">😽</option>
			<option title="" class="emji">😾</option>
			<option title="" class="emji">😿</option>
			<option title="" class="emji">🙀</option>
			<option title="" class="emji">🙅</option>
			<option title="" class="emji">🙆</option>
			<option title="" class="emji">🙇</option>
			<option title="" class="emji">🙈</option>
			<option title="" class="emji">🙉</option>
			<option title="" class="emji">🙊</option>
			<option title="" class="emji">🙋</option>
			<option title="" class="emji">🙌</option>
			<option title="" class="emji">🙍</option>
			<option title="" class="emji">🙎</option>
			<option title="" class="emji">🙏</option>